/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.ec.siatemaacademico0.vista;

import ec.edu.ec.siatemaacademico0.controlador.ControladorProfesores;

/**
 *
 * @author KARLA
 */
public class VProfesores extends javax.swing.JFrame {

    private ControladorProfesores controladorProfesor;
    /**
     * Creates new form VProfesores
     */
    public VProfesores() {
        initComponents();
        controladorProfesor = new ControladorProfesores(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public String getNombreProfesor(){
        return txtNombre.getText();
    }
    
    public String getCorreoPersonal(){
        return txtCorreoPersonal.getText();
    }
    
    public String getCedula(){
        return txtCedula.getText();
    }
    
    public String getCorreoInstitucional(){
        return txtCorreoInstitucional.getText();
    }
    
    public String getSuledo(){
        return txtSueldo.getText();
    }
    
    public String getEscalafon(){
        return txtEscalafon.getText();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
